### ISSUE TITLE
Use of query_posts() not recommended

### ISSUE THREAD

**Issue by sakinshrestha** [Codeinwp/islemag#29]
- Use `WP_Query` instead of `query_posts` in `template-blog.php` file
- Further, this method to modify blog posts is not appropriate even if using `WP_Query`. It is recommended to use [pre_get_posts](https://codex.wordpress.org/Plugin_API/Action_Reference/pre_get_posts) to alter blog page posts

**Comment by justintadlock** [comment]
Actually, this is the one legitimate use there is for `query_posts()`.  However, it shouldn't be needed at all.  

This template should be renamed to `home.php` and the following removed:

	/*
	Template Name: Blog
	*/

The correct template for the blog posts page is `home.php`.  WP will automatically use it.  And, you can use the normal WP query and loop instead of `query_posts()`.
